import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Drag n Drop | use case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="flex">
          <div className="min-w-80 w-80 h-screen p-4 bg-main-50">
            <div className="mb-10">
              <p className="text-sm">
                USE CASE
              </p>
              <h1 className="text-2xl font-bold rounded text-main-950">
                drag-n-drop
              </h1>
            </div>
            <Navigation />
          </div>
          <div className="flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
